name: Docs

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build docs
        run: |
          tox -e source

      - name: Preserve Docs
        # if: ${{ github.event_name == 'push' }}
        run: |
          tar -czvf docs.tar.gz -C source/_build html rtdpage

      - name: Save artifact
        # if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: ./docs.tar.gz

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      DOCS_REPO: OS-Q/Docs
      DOCS_DIR: source
      LATEST_DOCS_DIR: latest-docs
      RELEASE_BUILD: ${{ startsWith(github.ref, 'refs/tags/v') }}

    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs

      - name: Unpack artifact
        run: |
          mkdir ./${{ env.LATEST_DOCS_DIR }}
          tar -xzf ./docs.tar.gz -C ./${{ env.LATEST_DOCS_DIR }}

      - name: Delete Artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: docs

      - name: Checkout Docs
        continue-on-error: true
        uses: actions/checkout@v2
        with:
          repository: ${{ env.DOCS_REPO }}
          path: ${{ env.DOCS_DIR }}
          ref: gh-pages

      - name: Validate Docs
        run: |
          if [ -z "$(ls -A ${{ env.DOCS_DIR }})" ]; then
            echo "Docs folder is empty. Aborting!"
            exit 1
          fi

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.OSQ_REPO_TOKEN }}
          external_repository: ${{ env.DOCS_REPO }}
          publish_dir: ./${{ env.DOCS_DIR }}
          commit_message: Sync Docs
